language: cpp
compiler: clang++-6.0
before_script:
  - cd ..
  - git clone https://github.com/emilydolson/Empirical.git
  - cd Empirical && git checkout OEE
  - cd ../ecology_of_evolutionary_computation
script: make test CXX=clang++-6.0
